### PR TITLE
[HPT 1010 ] Create CDM OCR files

### PR DESCRIPTION
**Pull request by andjsmit**
Creates the files in directory of the ContentDM exported XML file. These files may be pulled into the ingest process by a later PR.

It also adds the path to the create OCR file to the ingest YML. [hpt-1011]

### CODE REVIEW

**Comment by rwingiupui** [comment]
+1  Created fulltext files - works as designed

**Review by randalldfloyd — APPROVED** [review]
@andjsmit All seems good to me but we're not as knowledgeable on the Content DM record so maybe someone up there should merge it, or you can merge it yourself. I did merge current master back into the PR.

**Comment by andjsmit** [comment]
Thanks @randalldfloyd . @rwingiupui would you be willing merging as it worked for you?

**Comment by rwingiupui** [comment]
Sorry for the delay, yes I'll merge the pull request.

**Pull request merged**
