### PR TITLE
[update_mysql2] Updates mysql2 gem, conservatively

### PR DESCRIPTION
**Pull request by aploshay**
Updates `mysql2` gem and the `BUNDLED WITH` statement.

### CODE REVIEW

**Review by mwoodiupui — APPROVED** [review]
Seems harmless.  We should be keeping up with dependency upgrades at judicious intervals.

**Comment by aploshay** [comment]
Updating rubocop results in a large number of new tickets, so we should probably discuss to what extent we want to resolve those tickets vs. disabling the new cops.

**Comment by aploshay** [comment]
Okay, I updated the `.rubocop.yml` file to get everything passing again as it was before the version upgrade, by doing the following:
* excluding some of the new files it started picking up:
  * `lib/tasks/*`
  * `app/views/search/*`
  * (I left in `Capfile`, `Gemfile`, and `Guardfile`, and just added a specific exclusion for `Naming/FileName
* disabled 85 cops that are either new or were modified, because they're generating tickets we didn't have before

For the excluded files: we probably want to fix their tickets.
For the 85 cops we're disabling: oh, man, fixing those is going to be a lot of work.  I'm not sure how highly we want to prioritize that.

**Review by dlpierce — APPROVED** [review]
I'm fine with these rubocop exclusions.

**Pull request merged**
