### PR TITLE
[HPT-1301] RSpec/AnyInstance

### PR DESCRIPTION
**Pull request by mwoodiupui**
https://bugs.dlib.indiana.edu/browse/HPT-1301
Some fixes.  Some places where I disabled the rule because the use seems legitimate.  A few places where I threw in the towel and disabled:  the fix would be too disruptive.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
This is a preview:  do not merge yet.  I'm chasing a Heisenbug that only shows up when running the full test suite.

**Comment by mwoodiupui** [comment]
Well, that was fun.  holding_location_renderer_spec.rb was failing to find stuff from the location authority.  HoldingLocationService holds a module-level reference to a HoldingLocationAuthority, so:  if a previous test has already caused HoldingLocationService to initialize, the usual `allow(Foo).to receive(:new).and_return(myMock)` doesn't work.  It works just fine when the test runs in isolation.  Fortunately it's possible to stub an mattr_accessor's methods just like any others.

**Review by wang58 — APPROVED** [review]
Looks good to me. It passed my rubocop check and rspec check.

**Review by wang58 — APPROVED** [review]

**Comment by mwoodiupui** [comment]
There was a merge conflict due to other concurrent RuboCop work.  I bypassed the attempted merge of master into the PR, rebased my copy of the PR on current master and [WARNING] force pushed.

**Pull request merged**
