### PR TITLE
Hpt-1021 uv 2.0.1

### PR DESCRIPTION
**Pull request by dlpierce**
I wanted to test this on carbon:8103, but it seemed like the dev loris is down. (?)

### CODE REVIEW

**Comment by randalldfloyd** [comment]
Has it been running at all since we put production? I can't remember but I'll have to look at it tomorrow at this point.

**Comment by dlpierce** [comment]
Pretty sure it was up when I was experimenting with the 2 color blurring stuff.

**Comment by randalldfloyd** [comment]
I forgot that Brian needed us to change the Apache port number on boron after Pages was put into production so the configured Loris URL was wrong.  I created a proxy configuration to obscure the host details so that it doesn't hurt us again sometime.  I set the correct URL in the config.yml on 8103 (so as to not divulge it here.)

**Review by randalldfloyd — COMMENTED** [review]
@IU-Libraries-Joint-Development/developers Bugs HPT-995 and HPT-996 still exist after upgrading UV to 2.0.1.  The question is whether or not to merge and deploy anyway since it doesn't fix those bugs and not knowing what negative impact, if any, there may be from doing so.  We can wait to see if HPT-972 is helped by it or not.

**Review by randalldfloyd — APPROVED** [review]

**Pull request merged**
