### PR TITLE
[HPT-1269] Pass Search to Universal Viewer

### PR DESCRIPTION
**Pull request by andjsmit**
Links catalog searching to universal viewer searching.

### CODE REVIEW

**Review by wang58 — COMMENTED** [review]
This works fine with the scanned resource. But if the resource is the multi volume work, when I do the search, I got the error when I open the multi volume work.

No route matches [GET] "/concern/multi_volume_works/d736664495/highlight/new"

If we do not care/consider the multi_volume_works,  then the change is good for me.

**Comment by andjsmit** [comment]
Yes - the route is missing for multi-volume works. The highlight search could either be skipped for multi-vol or the route created. I'll look to see which makes more sense.

**Review by wang58 — APPROVED** [review]
The search worked great for both scanned resource and multi-volume-work.

**Comment by aploshay** [comment]
@andjsmit The build failed due to networking issues, but I lack permission to initiate a rebuild

**Comment by dlpierce** [comment]
@aploshay Check that you're actually logged in to Circle, I had to go to the homepage to see that I was not. I restarted the build.

**Pull request merged**
