### PR TITLE
HPT-989 Add OCR generation to JP2 derivatives creation code

### PR DESCRIPTION
**Pull request by wang58**
RunOCRJob will create .hocr file for every .jp2 item in derivative and later we can see ocr text information in SOLR.

This change depends on Tesseract correctly installed. Tesseract needs to support libopenjp2. Type tesseract -v to see if it supports 'libopenjp2'

### CODE REVIEW

**Comment by wang58** [comment]
The tests failed on CircleCl is due to Tesseact does not support jp2 file. A special Tesseact should be installed (libopenjp2 support). 

Btw, my local tests passed with the correct Tesseact installation.

**Comment by rwingiupui** [comment]
I forgot to mention that the Tesseract installed on our demo server (http://pmp.ulib.iupui.edu/) supports jp2 files.  I installed libopenjp2 support when I configured Tesseract.

**Comment by andjsmit** [comment]
So to get the test to pass, I think the integration configuration is going to need to be updated. What would need to be added to this line for tesseract to work on JP2?

`sudo apt-get install libmagickwand-dev imagemagick redis-server tesseract-ocr tesseract-ocr-ita tesseract-ocr-eng sqlite3 libsqlite3-dev`

**Review by aploshay — APPROVED** [review]
Look good to me; my only question is whether we want to make the call to RunOCRJob dependent on the config setting for :store_original_files, or a separate new config setting (like, :run_ocr_job), a setting that's potentially job-specific by a line in the ingest YAML and/or rake task or ENV parameters.  But that could always be revisited later.

Also seems fine to override the coveralls 0.02% drop in reported coverage.

**Comment by andjsmit** [comment]
+1
I agree that OCR shoudl be made configurable. I've added it as a task to HPT-985. If @wang58  is OK with the very small test drop, I say merge this.

**Comment by wang58** [comment]
I am Ok with the small test drop. About OCR configuration part, I'd suggest to create another Jira.

**Pull request merged**
