### PR TITLE
[HPT-840] Add user menu choice to logout locally and from CAS.

### PR DESCRIPTION
**Pull request by mwoodiupui**
This code assumes that, if one is logged in, then one used CAS to do it.  I haven't yet found any way to discover the strategy by which the current session was logged in.

### CODE REVIEW

**Review by dlpierce — APPROVED** [review]
Looks good if everything works.
I thought Devise might need to be told about the custom session controller, similar to our custom omniauth controller. We might consider moving this controller to the users directory.

**Comment by mwoodiupui** [comment]
Why Users?  It doesn't seem to have any connection to the User model.

While looking around for the problem that broke the tests, I actually abolished the session controller and patched its sole method into Devise's session controller.  It seems to work.

**Comment by dlpierce** [comment]
I suggested the app/controllers/users directory since the Devise docs for setting a custom controller suggest it, and we already have some custom Devise code there.

**Comment by mwoodiupui** [comment]
Rebased.

**Pull request merged**
